name = "mediteach-ai"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-09"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"

[build.environment_variables]
NODE_VERSION = "20"